# Generated by Django 5.0.6 on 2024-07-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_storecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="storecard",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
