# Generated by Django 5.0.6 on 2024-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userphone"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPhone",
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_permission_set",
                to="auth.permission",
            ),
        ),
    ]
