# Generated by Django 5.0.6 on 2024-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=50)),
                ("personnel_number", models.IntegerField(max_length=10)),
                ("agent_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
    ]
