# Generated by Django 5.0.6 on 2024-07-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="phone_number",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="province",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="title",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.storecard",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="type",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="storecard",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
    ]
