# Generated by Django 5.0.6 on 2024-07-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_organization_created_at_store_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storecard",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
