# Generated by Django 5.0.6 on 2024-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_storecard_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="stores/"),
        ),
        migrations.AddField(
            model_name="store",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="stores/"),
        ),
    ]
